imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine_mongodb:
    connections:
        default:
            server: mongodb://int-app-glusterfs.gemmyx.com:8080
            options:
                connect: true
    default_database: wilano_test
    document_managers:
        default:
            auto_mapping: true