homepage:
    pattern:  /admin/
    defaults: { _controller: FDTAdminBundle:Default:index }

FDTAdmin_getMenu:
    pattern:  /admin/{bundleName}/getMenu
    defaults: { _controller: FDTAdminBundle:GetMenu:index}

admin_bundlesConfig:
    pattern:  /admin/getBundlesConfig/
    defaults: { _controller: FDTAdminBundle:GetBundlesConfig:index }
