homepage:
    pattern:  /admin/
    defaults: { _controller: FDTAdminBundle:Default:index }

FDTAdmin_getMenu:
    pattern:  /admin/{bundleName}/getMenu
    defaults: { _controller: FDTAdminBundle:GetMenu:index}

admin_config:
    pattern:  /admin/getConfig/
    defaults: { _controller: FDTAdminBundle:GetConfig:index }
