homepage:
    pattern:  /admin/
    defaults: { _controller: FDTAdminBundle:Default:index }

admin_menu:
    pattern:  /admin/getMenu/
    defaults: { _controller: FDTAdminBundle:GetMenu:index }

admin_bundlesConfig:
    pattern:  /admin/getBundlesConfig/
    defaults: { _controller: FDTAdminBundle:GetBundlesConfig:index }
